import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./components/layout/header";
import Footer from "./components/layout/footer";

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
       <main className="max-w-8xl max-auto border"> 
       <Navbar/>
        {children}
        <Footer/>
        </main> 
       </body>
    </html>
  );
}
